trigger:
  - main  # Runs the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu agent

steps:
  - checkout: self  # Pulls the latest code from the repo

  - script: |
      #!/bin/bash
      set -e  # Exit immediately if a command fails

      # Define file path
      VERSION_FILE="version.txt"

      # Ensure the version file exists
      if [ ! -f "$VERSION_FILE" ]; then
        echo "4+" > "$VERSION_FILE"
      fi

      # Read version from file
      VERSION=$(cat "$VERSION_FILE")

      # Extract number, increment it
      NUMERIC_VERSION=$(echo "$VERSION" | grep -o '[0-9]\+')
      NEW_VERSION=$((NUMERIC_VERSION + 1))

      # Update the file
      echo "${NEW_VERSION}+" > "$VERSION_FILE"

      # Configure Git
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps Pipeline"

      # Ensure we are on the correct branch
      git checkout main || git checkout -b main

      # Add, commit, and push changes using the GitHub PAT
      git add "$VERSION_FILE"
      git commit -m "Increment version to ${NEW_VERSION}+"

      # Use GitHub PAT for authentication
      git push https://$(GITHUB_PAT)@github.com/cybagemobilecoe/DevOps_experience.git main
    displayName: 'Increment Version in Text File'
    env:
      GITHUB_PAT: $(GITHUB_PAT)  # Map the Azure DevOps secret variable
