trigger:
  - main  # Runs when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Ensures the repo is checked out

  - script: |
      #!/bin/bash
      set -e  # Exit on error

      VERSION_FILE="version.txt"

      # Ensure the file exists
      if [ ! -f "$VERSION_FILE" ]; then
        echo "4+" > "$VERSION_FILE"
      fi

      # Read and increment version
      VERSION=$(cat "$VERSION_FILE")
      NUMERIC_VERSION=$(echo "$VERSION" | grep -o '[0-9]\+')
      NEW_VERSION=$((NUMERIC_VERSION + 1))