trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update File in Repo"
  jobs:
  - job: UpdateChar
    displayName: "Update 31st Character in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true  # Ensures Git authentication works

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Define the absolute file path
        filePath="$(Build.SourcesDirectory)/experience.txt"
        echo "Checking file: $filePath"

        # Ensure the file exists
        if [ ! -f "$filePath" ]; then
          echo "Error: File '$filePath' not found."
          exit 1
        fi

        # Read the first line of the file
        first_line=$(head -n 1 "$filePath")

        # Ensure the line has at least 31 characters
        if [ ${#first_line} -lt 31 ]; then
          echo "Error: First line of the file has less than 31 characters."
          exit 1
        fi

        # Extract the 31st character (index 30)
        char_31=${first_line:30:1}

        # Convert to number and increment
        if ! [[ $char_31 =~ ^[0-9]+$ ]]; then
          echo "Error: The 31st character is not a valid number."
          exit 1
        fi
        new_value=$((char_31 + 1))

        # Modify the file content
        updated_line="${first_line:0:30}$new_value${first_line:31}"
        { echo "$updated_line"; tail -n +2 "$filePath"; } > "$filePath.tmp" && mv "$filePath.tmp" "$filePath"

        # Display updated content
        echo "Updated file content:" && cat "$filePath"
      displayName: "Process File"

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Debugging: Check current Git status
        git status

        # Set Git config
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        # Ensure we are on the main branch
        git checkout main || git checkout -b main

        # Debugging: Show current branch and changes
        git branch
        git diff

        # Add, commit, and push changes
        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || true
        git push origin main || echo "Push failed, check permissions"
      displayName: "Commit and Push Changes"
