trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update Experience in Repo"
  jobs:
  - job: UpdateExperience
    displayName: "Increment Experience in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0  # Ensures full checkout

    - script: |
        filePath="$BUILD_SOURCESDIRECTORY/experience.txt"

        # Create the file if it does not exist
        if [ ! -f "$filePath" ]; then
          echo "Creating experience.txt..."
          echo "Need Sr. DevOps Engineer with 4+ years of experience of Jenkins, GitHub Actions, AWS services - S3, EC2, RDS, IAM Identity Center, Route 53, CloudWatch, Lambda, SES, ElastiCache, Data Transfer, VPC, ELB, Global Accelerator, KMS, WAF, Kinesis, Config, CloudFront" > "$filePath"
        fi

        echo "Checking file: $filePath"

        # Read the file content
        content=$(cat "$filePath")

        # Extract experience number using regex (matches '4+', '5+', etc.)
        if [[ "$content" =~ ([0-9]+)\+ ]]; then
          exp_years=${BASH_REMATCH[1]}  # Capture the number
          new_exp=$((exp_years + 1))    # Increment it
          updated_content=$(echo "$content" | sed -E "s/${exp_years}\+/${new_exp}+/")  # Replace in file
          echo "$updated_content" > "$filePath"  # Save changes
          echo "Updated experience to ${new_exp}+ years."
        else
          echo "Error: Could not find experience format (e.g., '4+') in file."
          exit 1
        fi
      displayName: "Process Experience File"

    - script: |
        git status
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        git checkout main || git checkout -b main
        git branch
        git diff

        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || echo "No changes to commit"
        git push origin main || echo "Push failed"
      displayName: "Commit and Push Changes"
