trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update File in Repo"
  jobs:
  - job: UpdateExperience
    displayName: "Update Experience in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0

    - script: |
        filePath="$BUILD_SOURCESDIRECTORY/experience.txt"

        # Create the file if it does not exist
        if [ ! -f "$filePath" ]; then
          echo "Creating experience.txt..."
          echo "Sr. DevOps Engineer with 4+ years of experience of Jenkins, GitHub Actions, AWS services - S3, EC2, RDS, IAM Identity Center, Route 53, CloudWatch, Lambda, SES, ElastiCache, Data Transfer, VPC, ELB, Global Accelerator, KMS, WAF, Kinesis, Config, CloudFront" > "$filePath"
          echo "Strong communication skills" >> "$filePath"
          echo "Ability to work effectively in a collaborative, client-facing role." >> "$filePath"
          echo "Excellent problem-solving and analytical skills." >> "$filePath"
          echo "Familiarity with agile development methodologies." >> "$filePath"
          echo "Independent contributor" >> "$filePath"
        fi

        echo "Checking file: $filePath"

        # Read the first line of the file
        first_line=$(head -n 1 "$filePath")

        # Extract the experience number from the first line
        experience=$(echo "$first_line" | grep -oP '\d+(?=\+ years of experience)')

        if [[ -z "$experience" ]]; then
          echo "Error: Experience not found in file."
          exit 1
        fi

        # Increment the experience
        new_experience=$((experience + 1))

        # Replace the old experience with the new experience
        updated_line=$(echo "$first_line" | sed -E "s/${experience}\+/${new_experience}+/")

        # Update the file with the modified content
        { echo "$updated_line"; tail -n +2 "$filePath"; } > "$filePath.tmp" && mv "$filePath.tmp" "$filePath"

        # Display updated content
        echo "Updated file content:" && cat "$filePath"
      displayName: "Process File"

    - script: |
        git status
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        git checkout main || git checkout -b main
        git branch
        git diff

        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || echo "No changes to commit"
        git push origin main || echo "Push failed"
      displayName: "Commit and Push Changes"