trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update Experience in Repo"
  jobs:
  - job: UpdateExperience
    displayName: "Increment Experience in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0  # Ensures full checkout

    - script: |
        filePath="$BUILD_SOURCESDIRECTORY/experience.txt"

        # Create file if it does not exist
        if [ ! -f "$filePath" ]; then
          echo "Creating experience.txt..."
          echo "Need Sr. DevOps Engineer with 4+ years of experience of Jenkins, GitHub Actions, AWS services - S3, EC2, RDS, IAM Identity Center, Route 53, CloudWatch, Lambda, SES, ElastiCache, Data Transfer, VPC, ELB, Global Accelerator, KMS, WAF, Kinesis, Config, CloudFront" > "$filePath"
        fi

        echo "Checking file: $filePath"

        # Debug: Print file content
        echo "Current file content:"
        cat "$filePath"

        # Extract experience number using regex (ensuring no extra spaces)
        exp_years=$(grep -oE '[0-9]+\+' "$filePath" | head -1 | tr -d '+')

        # Debug: Show extracted value
        echo "Extracted experience: $exp_years"

        if [[ -z "$exp_years" ]]; then
          echo "Error: Could not find experience format (e.g., '4+') in file."
          exit 1
        fi

        # Increment the experience number
        new_exp=$((exp_years + 1))

        # Replace in file (ensuring correct format)
        sed -i "s/${exp_years}\+/${new_exp}+/g" "$filePath"

        # Show updated file content
        echo "Updated experience to ${new_exp}+ years."
        cat "$filePath"
      displayName: "Process Experience File"

    - script: |
        git status
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        git checkout main || git checkout -b main
        git branch
        git diff

        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || echo "No changes to commit"
        git push origin main || echo "Push failed"
      displayName: "Commit and Push Changes"
