trigger:
  - main  # Runs on the main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self  # Ensures the repo is checked out

  - script: |
      #!/bin/bash
      set -e  # Exit on error

      # Define file path
      VERSION_FILE="version.txt"

      # Ensure the version file exists
      if [ ! -f "$VERSION_FILE" ]; then
        echo "4+" > "$VERSION_FILE"
      fi

      # Read version from file
      VERSION=$(cat "$VERSION_FILE")

      # Extract number, increment it
      NUMERIC_VERSION=$(echo "$VERSION" | grep -o '[0-9]\+')
      NEW_VERSION=$((NUMERIC_VERSION + 1))

      # Update the file
      echo "${NEW_VERSION}+" > "$VERSION_FILE"

      # Configure Git
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps Pipeline"

      # Ensure we are on the correct branch
      git checkout main || git checkout -b main

      # Add, commit, and push changes
      git add "$VERSION_FILE"
      git commit -m "Increment version to ${NEW_VERSION}+"

      # Set remote URL with GitHub PAT securely
      git remote set-url origin https://$(GITHUB_PAT)@github.com/cybagemobilecoe/DevOps_experience.git

      # Push changes
      git push origin main
    displayName: 'Increment Version in Text File'
    env:
      GITHUB_PAT: $(GITHUB_PAT)  # Ensure it's passed as an environment variable
