trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  filePath: 'experience.txt'  # Ensure the correct relative path to the file

stages:
- stage: UpdateFile
  displayName: "Update File in Repo"

  jobs:
  - job: UpdateChar
    displayName: "Update 30th Character in File"

    steps:
    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    - script: |
        #!/bin/bash

        # Define the file path from the variable
        FILE_PATH="${{ variables.filePath }}"  # Use the correct file path from variables

        # Check if file exists
        if [ ! -f "$FILE_PATH" ]; then
          echo "Error: File '$FILE_PATH' not found."
          exit 1
        fi

        # Read the first line of the file
        first_line=$(head -n 1 "$FILE_PATH")

        # Ensure the line has at least 30 characters
        if [ ${#first_line} -lt 30 ]; then
          echo "Error: First line of the file has less than 30 characters."
          exit 1
        fi

        # Extract the 30th character
        char_30=${first_line:30:1}

        # Convert the character to a number
        if ! [[ $char_30 =~ ^[0-9]+$ ]]; then
          echo "Error: The 30th character is not a valid number."
          exit 1
        fi

        new_value=$((char_30 + 1))

        # Replace the 30th character in the first line
        updated_line=$(echo "$first_line" | sed "s/./$new_value/31")

        # Output the updated content
        echo "=== Original File Content ==="
        cat "$FILE_PATH"
        echo ""
        echo "=== Updated File Content ==="
        echo "$updated_line"
      displayName: "Process and Display File Changes"

