trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update Experience Level in experience.txt"
  jobs:
  - job: UpdateExperience
    displayName: "Update Experience Level in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true  # Ensures Git authentication works

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Define the absolute file path
        filePath="$(Build.SourcesDirectory)/experience.txt"
        echo "Checking file: $filePath"

        # Ensure the file exists
        if [ ! -f "$filePath" ]; then
          echo "Error: File '$filePath' not found."
          exit 1
        fi

        # Read the file content
        content=$(cat "$filePath")

        # Print original content for debugging
        echo "Original content:"
        echo "$content"

        # Use sed to find and replace experience level (e.g., '4+' -> '5+', '5+' -> '6+')
        updated_content=$(echo "$content" | sed -E 's/([4-5]+)\+/echo $((${BASH_REMATCH[1]}+1))+/ge')

        # If there was any change, update the file
        if [ "$content" != "$updated_content" ]; then
          echo "$updated_content" > "$filePath"
          echo "File updated successfully"
        else
          echo "No experience level to update"
        fi

        # Display updated content
        echo "Updated file content:"
        echo "$updated_content"
      displayName: "Process File"

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Debugging: Check current Git status
        git status

        # Set Git config
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        # Ensure we are on the main branch
        git checkout main || git checkout -b main

        # Debugging: Show current branch and changes
        git branch
        git diff

        # Add, commit, and push changes
        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || true
        git push origin main || echo "Push failed, check permissions"
      displayName: "Commit and Push Changes"
