trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update File in Repo"
  jobs:
  - job: UpdateChar
    displayName: "Update 31st Character in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true
      fetchDepth: 0  # Ensures full checkout

    - script: |
        echo "Build sources directory: $BUILD_SOURCESDIRECTORY"
        echo "Listing files in workspace:"
        ls -la "$BUILD_SOURCESDIRECTORY"
      displayName: "Debug File Path"

    - script: |
        filePath="$BUILD_SOURCESDIRECTORY/experience.txt"

        # Create the file if it does not exist
        if [ ! -f "$filePath" ]; then
          echo "Creating experience.txt..."
          echo "Experience Level: 1" > "$filePath"
        fi

        echo "Checking file: $filePath"

        # Read the first line of the file
        first_line=$(head -n 1 "$filePath")

        # Ensure the line has at least 31 characters
        if [ ${#first_line} -lt 31 ]; then
          echo "Error: First line of the file has less than 31 characters."
          exit 1
        fi

        # Extract the 31st character (index 30)
        char_31=${first_line:30:1}

        # Convert to number and increment
        if ! [[ $char_31 =~ ^[0-9]+$ ]]; then
          echo "Error: The 31st character is not a valid number."
          exit 1
        fi
        new_value=$((char_31 + 1))

        # Modify the file content
        updated_line="${first_line:0:30}$new_value${first_line:31}"

        # Update the file with the modified content
        { echo "$updated_line"; tail -n +2 "$filePath"; } > "$filePath.tmp" && mv "$filePath.tmp" "$filePath"

        # Display updated content
        echo "Updated file content:" && cat "$filePath"
      displayName: "Process File"

    - script: |
        git status
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        git checkout main || git checkout -b main
        git branch
        git diff

        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || echo "No changes to commit"
        git push origin main || echo "Push failed"
      displayName: "Commit and Push Changes"
