trigger:
  - main  # Runs the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Using Ubuntu as the build agent

steps:
  - checkout: self  # Pull the latest code from the repository
  
  - script: |
      #!/bin/bash

      # Define file path
      VERSION_FILE="version.txt"

      # Check if version.txt exists, create it with 4+ if not
      if [ ! -f "$VERSION_FILE" ]; then
        echo "4+" > "$VERSION_FILE"
      fi

      # Read version from file
      VERSION=$(cat "$VERSION_FILE")

      # Extract number, increment it
      NUMERIC_VERSION=$(echo "$VERSION" | grep -o '[0-9]\+')
      NEW_VERSION=$((NUMERIC_VERSION + 1))

      # Update the file
      echo "${NEW_VERSION}+" > "$VERSION_FILE"

      # Configure Git
      git config --global user.email "your-email@example.com"
      git config --global user.name "Azure DevOps Pipeline"

      # Ensure we're on the correct branch (e.g., main or master)
      git checkout $(git rev-parse --abbrev-ref HEAD) || git checkout -b main

      # Commit and push changes
      git add "$VERSION_FILE"
      git commit -m "Increment version to ${NEW_VERSION}+"
      git push origin HEAD:main  # Ensure the correct branch is targeted
    displayName: 'Increment Version in Text File'
    failOnStderr: true  # Fail the task if there's an error in the script
