trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UpdateFile
  displayName: "Update File in Repo"
  jobs:
  - job: UpdateChar
    displayName: "Update Experience Level in experience.txt"
    steps:
    - checkout: self
      persistCredentials: true  # Ensures Git authentication works

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Fetch the latest changes from the repository
        git fetch origin

        # Ensure we're on the main branch and pull latest changes
        git checkout main || git checkout -b main
        git pull origin main

        # Define the absolute file path for experience.txt
        filePath="$(Build.SourcesDirectory)/experience.txt"
        echo "Checking file: $filePath"

        # Ensure the file exists
        if [ ! -f "$filePath" ]; then
          echo "Error: File '$filePath' not found."
          exit 1
        fi

        # Read the content of the file
        file_content=$(cat "$filePath")

        # Replace the experience levels (4+ -> 5+, 5+ -> 6+)
        updated_content=$(echo "$file_content" | sed -E 's/(4\+)( years)/5\+\2/g' | sed -E 's/(5\+)( years)/6\+\2/g')

        # If there are no changes, exit
        if [ "$file_content" == "$updated_content" ]; then
          echo "No experience level to update"
          exit 0
        fi

        # Update the file with the modified content
        echo "$updated_content" > "$filePath"

        # Display updated content for confirmation
        echo "Updated file content:"
        cat "$filePath"
      displayName: "Process File"

    - script: |
        #!/bin/bash
        set -e  # Exit on error

        # Check current Git status
        git status

        # Set Git config (if not already configured)
        git config --global user.name "Azure DevOps"
        git config --global user.email "cybage.mobile.coe@gmail.com"

        # Ensure we're on the correct branch (main) and push changes
        git checkout main || git checkout -b main
        git pull origin main

        # Commit and push the changes
        git add experience.txt
        git commit -m "Updated experience level in experience.txt" || echo "No changes to commit"
        git push origin main || echo "Push failed, check permissions"
      displayName: "Commit and Push Changes"
